@api_server = http://127.0.0.1:8000/api/employee/
POST {{api_server}} HTTP/1.1
content-type: application/json

{
    "name": "Updated Name",
    "age": "35",
    "phone": "987654321",
    "identity": "FULL",
    "salary_type": "MONTH"
}