@api_server = http://127.0.0.1:8002/api/employee
@employee_id =6
PUT  {{api_server}}/{{employee_id}} HTTP/1.1
content-type: application/json

{
    "name": "Updated Name",
    "age": "35",
    "phone": "987654321",
    "identity": "FULL",
    "salary_type": "MONTH"
}