# Generated by Django 3.2.25 on 2025-03-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('identity', models.CharField(choices=[('FULL', '正职'), ('PART', '兼职')], default='FULL', max_length=4)),
                ('salary_type', models.CharField(choices=[('MONTH', '月薪'), ('HOUR', '时薪')], default='MONTH', max_length=5)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
